name: CI - Test FastAPI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Crear entorno virtual e instalar dependencias
      run: |
        python -m venv venv
        ./venv/bin/pip install --upgrade pip
        ./venv/bin/pip install -r requirements.txt

    - name: Iniciar servidor FastAPI
      run: |
        ./venv/bin/uvicorn app:app --host 0.0.0.0 --port 8000 &
        sleep 20

    - name: Ejecutar pruebas de API
      run: |
        ./venv/bin/pytest --maxfail=5 --disable-warnings --alluredir=allure-results
