name: CI - Test FastAPI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Iniciar servidor FastAPI
      run: |
        source venv/bin/activate
        nohup uvicorn api.main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &

    - name: Esperar a que el servidor esté listo
      run: |
        sudo apt-get install -y curl
        for i in {1..20}; do
          if curl -s http://localhost:8000/docs > /dev/null; then
            echo "Servidor listo!"
            break
          else
            echo "Esperando servidor... intento $i"
            sleep 3
          fi
        done

    - name: Ejecutar pruebas de API
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings --alluredir=allure-results
