name: CI - Test FastAPI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Iniciar servidor FastAPI
      run: |
        source venv/bin/activate
        uvicorn api.routes.main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Da tiempo a que arranque el servidor

    -  name: Verificar que el servidor esté levantado
       run: |
        curl --fail http://127.0.0.1:8000 || (echo "FastAPI NO respondió" && exit 1)

    - name: Ejecutar pruebas de API
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings --alluredir=allure-results
