name: CI - Test FastAPI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
         

    - name: Iniciar servidor FastAPI
      run: |
       uvicorn api.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
       for i in {1..30}; do
          if grep -q "Application startup complete" server.log; then
            echo "Servidor arrancó completamente!"
            break
          fi
            echo "Esperando a que FastAPI arranque... intento $i"
            sleep 1
       done
       cat server.log

    - name: Verificar que FastAPI respondió
      run: |
        curl --fail http://127.0.0.1:8000 || (echo "FastAPI NO respondió" && exit 1)

    - name: Ejecutar pruebas
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings --alluredir=allure-results
