name: Run API tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        uvicorn api.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
        echo "Esperando que FastAPI arranque..."
        for i in {1..15}; do
          if curl --fail http://127.0.0.1:8000; then
            echo "FastAPI arrancó exitosamente."
            break
          fi
          echo "Intento $i: FastAPI aún no responde..."
          sleep 1
        done
        echo "📜 Log de servidor FastAPI:"
        cat server.log

    - name: Run tests
      env:
        BASE_URL: http://127.0.0.1:8000
      run: pytest
